### PR TITLE
Feature/homey sdk3 support

### PR DESCRIPTION
**Pull request by bramoosterhuis**
I can control my devices with the SDK 3 again...

### CODE REVIEW

**Comment by bramoosterhuis** [comment]
Maybe you can you use it for 
https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/210

**Comment by JohanBendz** [comment]
Hi @bramoosterhuis and thanks for the support and the PR! :)

I have looked through it and had to look twice as much of the code was very similar to what I have been doing, guess there is just so many ways one can do stuff like this :) ;)

I have the lights fixed since before my vacation, just came back home and is now looking to make the sensors and buttons work as I want. I tried your code and see that dim buttons do not trigger the flow cards and that the temperature and lux is not updated for the motion sensor. I would happily use your code for those devices if you have the time to fix them.

Again, thanks for helping! :)

**Comment by pardeike** [comment]
Hi, I currently have three options:
- revert to 4.x (bleh)
- (un)screw my hue lamps to turn them on/off (I don't have normal lights)
- install `bramoosterhuis:feature/homey-sdk3-support` myself (about to do that)
- wait for you to give us at least a rudimentary working app
- other options?
What do you recommend?
/Andreas

**Comment by JohanBendz** [comment]
Hi @pardeike, Well, if you ask me you should have waited for the release of my app before upgrading to v5 ;)

I will release an update within the week.

**Comment by pardeike** [comment]
I am a developer, I don't wait and rather spend my time in darkness a week.

**Comment by JohanBendz** [comment]
> I am a developer, I don't wait and rather spend my time in darkness a week.

LOL.. well good thing then we have bright summers :D

**Comment by zeppie** [comment]
Is 1.6.1 the version with sdk3 support? My lightstrips are still not working. How do I get them working again, I have no bridge...
Hopefully it is possible without er-installing them (lots of flows...)
Thanks for the hard work!

**Comment by shaarkys** [comment]
You can : 
- factory reset your Homey and go back to non-experimental version
- download and install https://github.com/bramoosterhuis/com.philips.hue.zigbee/tree/feature/homey-sdk3-support from @bramoosterhuis via CLI temporarily
- wait for @JohanBendz update (I understood it will come this month, which is fantastic)
- wait in the darkness ;-)

**Comment by shaarkys** [comment]
https://github.com/sebbebebbe/com.philips.hue.zigbee/issues/210

**Comment by JohanBendz** [comment]
Hi @zeppie, no.. the 1.6.1 version is the old testversion with SDK2 support. I had to upgrade it to Live version to make room for the upcoming SDK3 / Firmware v5 test version of the app.

I hope to have a test version out in the wild within days. No v5 app will be published as Live before Athom release the stable v5.

If you upgraded to v5 by accident you can also downgrade using Homey backup (if you have this service).

**Comment by zeppie** [comment]
makes perfect sense, I'll keep a close eye on the test-version. 
Again thanks for all the hard work. Small detail: make sure to update the readme.md

Goodluck

**Pull request closed without merging**
