### PR TITLE
Added support for Filament Lamp G93 / LWO001

### PR DESCRIPTION
**Pull request by Gemeni123**
Hi

Added support for G93 ... Maybe the svg icon can be nicer and smaller. Did my best :)

### CODE REVIEW

**Comment by HarlandT** [comment]
How can i implement this on my Homey?

**Comment by JohanBendz** [comment]
Looks good @Gemeni123 👍

**Comment by JohanBendz** [comment]
> How can i implement this on my Homey?

@HarlandT Wait for next release of the app or install the fork version using CLI (https://community.athom.com/t/how-to-cli-install-method/198)

**Comment by HarlandT** [comment]
Thanks! Will look at this tomorrow!

**Comment by HarlandT** [comment]
@JohanBendz How do i find the fork version to Download?

**Comment by sebbebebbe** [comment]
Nice addition, i will try make the commits less intrusive since the entire app.json gives a diff.
And another thing, always create your own branch based on the dev branch.

**Comment by sebbebebbe** [comment]
The filament G93 is now merged into Dev branch and will be added to the next release. So I will close this PR.

**Comment by Gemeni123** [comment]
Thanks for the feedback @sebbebebbe will use dev-branch next time. 

Nice to have it included in coming release 😃

**Pull request closed without merging**
