### PR TITLE
Add support for LCL001

### PR DESCRIPTION
**Pull request by zepign**
Adds support for the new LightStrips Plus V4 (BT), LCL001. Verified that its working on my homey.

### CODE REVIEW

**Comment by AvieNL** [comment]
I tried to connect this Lightstrip Plus (LCL001). But only showed as Unknown Zigbee. Any sollution for this issue?

**Comment by AvieNL** [comment]
> I tried to connect this Lightstrip Plus (LCL001). But only showed as Unknown Zigbee. Any sollution for this issue?

Maybe... I have v1.4.9, can't force an update. When is the new version available?

**Comment by JohanBendz** [comment]
Thanks @zepign for the PR, I will add the device to the next version of the app. Since I am rewriting some code to support SDK 3 / Homey v5. I will however not merge the PR.

**Comment by JohanBendz** [comment]
Now added to upcoming version. Thx @zepign

**Pull request closed without merging**
