### PR TITLE
Fix Hue1744630P7

### PR DESCRIPTION
**Pull request by zepign**
Fixes Hue outdoor wall Fuzo lamp 1744630P7.
It is probable that the same issue exists for the other Fuzo devices as well, at least in regards to Color but have not verified this yet.

### CODE REVIEW

**Comment by JohanBendz** [comment]
Hi @zepign and thanks for your contribution, I have been looking into this already since others have complained about the device not working.

I get very mixed information from everyone, some send me pictures with Device ID: 256 and Profile ID: 49246 and some send me information claiming Device ID: 257 and Profile ID: 260.

What I am sure of is that the devices by misstake use HueColor (as you also found) when they all should use HueWhite, this is now corrected and will be pushed to next Test version.

But.. the ID's trouble me.,, I will push the test version (v.1.5.7) using Device ID: 256 and Profile ID: 49246 but change to HueWhite. If you could try that one out and get back to me I would be more than happy!

https://homey.app/a/com.philips.hue.zigbee/test/

Again, thanks for your help! // Johan

**Comment by zepign** [comment]
Ah, interesting with the ID's! I tried that locally at first but it didn't work. I'll see if I can try it again with your test build later.
Im curious if the ID's can differ between regions? I bought my devices in sweden and got 257 & 260. Im not too familiar with zigbee yet so I apologise if this is a ridiculous question :)

**Comment by JohanBendz** [comment]
@zepign Not at all ridiculous, when it comes to these devices I'd say I'v run into much stranger stuff... It CAN be that there are several versions of the same device with different ID's, could be time of production, region, or whatever.. If we can verify this I can add those ID's to the app and see if that helps.

(from Sweden myself btw :) )

**Comment by JohanBendz** [comment]
Hi @zepign, did you get around to try the new test version? Does it work for you?

**Comment by JohanBendz** [comment]
Hi again @zepign, I have now added both versions of the Device and Profile ID's to the code. Let's see if this works for everyone..

**Pull request closed without merging**
